### ISSUE TITLE
Not fetching stock quotes anymore

### ISSUE THREAD

**Issue by iSchorsch** [conradreisch/EODDataPortfolio-MoneyMoney#4]
unfortunately the beloved extension for money money is not fetching the stock quotes anymore. It shows the value 0.

**Comment by dark-m0de** [comment]
Hi @iSchorsch, thanks for bringing this up! I can confirm that the extension does not work currently.
However, it looks like the [eoddata website](https://eoddata.com/) is not working properly. Therefore, I can't do much about it in the moment.
Lets keep this issue open and I'll check again later this week.
BR

**Comment by dark-m0de** [comment]
eoddata website works again. Plugin works as well. closing the issue

**Comment by jaid33** [comment]
Looks like it's not working again. I didn't get any values since 2 days.
Can someone confirm?

**Comment by iSchorsch** [comment]
same here. After updating to new MoneyMoney version (2.4.29). 
Reverting to old MoneyMoney version (2.4.28) and everything is fine.

**Comment by dark-m0de** [comment]
Hi @iSchorsch and @jaid33, thanks for bringing this up. Currently I'm running version 2.4.28 from the AppStore and can't reproduce the error. Before I manually install the new version, is there maybe an error message that you can share?
BR

**Comment by dark-m0de** [comment]
P.S.: When I check the [download page](https://moneymoney-app.com/download/) and the [versions page](https://moneymoney-app.com/changelog/), those only offer 2.4.28 as well. Maybe there was a general issue with 2.4.29. However, I'll reach out to Mr. Haller to double check.

**Comment by dark-m0de** [comment]
After reaching out to Mr. Haller, I learned that 2.4.29 is changing the way how MoneyMoney deals with forreign currencies (see release notes: https://moneymoney-app.com/beta/). 

I already created an update and now need to wait for a signed version. I will notify you after I can release the update.

**Comment by dark-m0de** [comment]
`v1.4` is now released and should fix the issue. Looking forward to a quick feedback.

**Comment by jaid33** [comment]
Hi, 
thanks, it's working again!
Is there a smart way to fix the days with missing data in the bar chart?

**Comment by iSchorsch** [comment]
@dark-m0de I can confirm as well that it is working again with MoneyMoney 2.4.29 - thank you for your effort and time!
@jaid33 I have switched to monthly view. It's more relaxing anyways to watch stocks like that :-)

**Comment by dark-m0de** [comment]
> Is there a smart way to fix the days with missing data in the bar chart?

@jaid33 - This data is in the database and from an extension point of view, there is not much that I can do about it. However, maybe you can export the data from this account, edit it and then import it again. 

P.S.: There should be a `MoneyMoney-Backup.sqlite` file that was created before the switch to 2.4.29. If you rename that file to `MoneyMoney.sqlite`, you should be good as well.
