### ISSUE TITLE
Currency Converstion

### ISSUE THREAD

**Issue by sdoering1** [conradreisch/EODDataPortfolio-MoneyMoney#6]
I have a problem with the currency conversion.
For example, I have 446 shares of ARCC, the closing price yesterday is $19.38, conversion rate 1.095.
So my shares are worth the following:

446x19.38/1.095= 7893 EUR

In MoneyMoney, however, only a value of 7696 EUR is displayed.

The share value in EUR would be 19.38/1.095=17.7 EUR

However, MoneyMoney shows me 17.26 EUR.

Where is the error?

![1](https://github.com/dark-m0de/EODDataPortfolio-MoneyMoney/assets/50071054/0bad296d-24d8-4111-9a5e-166fb84aac25)

Best Regards
Siggi

**Comment by dark-m0de** [comment]
Thanks for bringing this up.

I just added 446 ARCC shares to my portfolio via `NASDAQ/ARCC(446)[USD]`. Adding the `[USD]` at the end has the effect that the amount (shares times price) is going to be divided by the exchange rate: https://eoddata.com/stockquote/FOREX/EURUSD.htm

The result is this:
<img width="539" alt="image" src="https://github.com/dark-m0de/EODDataPortfolio-MoneyMoney/assets/40696850/1d2f2e6e-7873-40f8-8f63-93fd37386b58">

This seems to be correct. Isn't it?

**Comment by dark-m0de** [comment]
P.S.: You have to manually add foreign currencies, since EODData is unfortunately not providing any information of the stock currency and there are "exchanges" that have multiple currencies.

**Comment by sdoering1** [comment]
That is exactly what I have also entered.
Nevertheless, MoneyMoney shows me other values.

![2](https://github.com/dark-m0de/EODDataPortfolio-MoneyMoney/assets/50071054/68e1e81d-38b6-4042-a32f-1190ca3cd428)

![3](https://github.com/dark-m0de/EODDataPortfolio-MoneyMoney/assets/50071054/fdb686a5-5ae1-4b0c-a831-1cd68c42c6dd)

**Comment by sdoering1** [comment]
Updated to version 1.4 and everything is fine.
Sorry!!!

**Comment by dark-m0de** [comment]
No worries. I appreciate the feedback also wasn't aware that the recent changes in MoneyMoney, that required me to release v1.4, also lead to using different exchange rate.
